### PR TITLE
Transfer IP: router

### PR DESCRIPTION
**Pull request by UnsignedByte**

### CODE REVIEW

**Review by jjm469 — COMMENTED** [review]
Looks good.

**Review by jjm469 — CHANGES_REQUESTED** [review]
Needs a src/sink tb

**Comment by UnsignedByte** [comment]
Should discuss whether or not to clip off address bits before merging this.

**Comment by UnsignedByte** [comment]
Final decision on router behavior - we won't clip the address bits (spoke to professor batten).

**Review by jjm469 — APPROVED** [review]
I think everything looks good!

**Pull request merged**
